export const companies = [
  {
    id: 1,
    nombre: "Grupo Industrial Monterrey",
    industria: "Manufactura",
    tamano: "500-1000 emp.",
    ingresos: "$120M USD",
    scoreIA: 94,
    estado: "Investigada",
    sitio: "grupoindustrialmonterrey.mx",
    contactos: 3,
    fechaAgregada: "2025-04-02",
  },
  {
    id: 2,
    nombre: "LogiTrans México",
    industria: "Logística",
    tamano: "200-500 emp.",
    ingresos: "$45M USD",
    scoreIA: 87,
    estado: "Contactada",
    sitio: "logitrans.mx",
    contactos: 5,
    fechaAgregada: "2025-04-05",
  },
  {
    id: 3,
    nombre: "Salud Integral SA",
    industria: "Salud",
    tamano: "100-200 emp.",
    ingresos: "$28M USD",
    scoreIA: 82,
    estado: "En proceso",
    sitio: "saludintegral.mx",
    contactos: 2,
    fechaAgregada: "2025-04-08",
  },
  {
    id: 4,
    nombre: "Constructora Azteca",
    industria: "Construcción",
    tamano: "200-500 emp.",
    ingresos: "$67M USD",
    scoreIA: 78,
    estado: "Investigada",
    sitio: "constructoraazteca.mx",
    contactos: 4,
    fechaAgregada: "2025-04-10",
  },
  {
    id: 5,
    nombre: "TechSoluciones MX",
    industria: "Tecnología",
    tamano: "50-100 emp.",
    ingresos: "$12M USD",
    scoreIA: 91,
    estado: "Convertida",
    sitio: "techsoluciones.mx",
    contactos: 6,
    fechaAgregada: "2025-04-12",
  },
  {
    id: 6,
    nombre: "Distribuidora Nacional",
    industria: "Distribución",
    tamano: "500-1000 emp.",
    ingresos: "$89M USD",
    scoreIA: 76,
    estado: "Contactada",
    sitio: "distrinacional.mx",
    contactos: 3,
    fechaAgregada: "2025-04-14",
  },
  {
    id: 7,
    nombre: "Pharma Innovación",
    industria: "Farmacéutica",
    tamano: "200-500 emp.",
    ingresos: "$156M USD",
    scoreIA: 88,
    estado: "En proceso",
    sitio: "pharmainnovacion.mx",
    contactos: 7,
    fechaAgregada: "2025-04-16",
  },
  {
    id: 8,
    nombre: "Manufactura del Norte",
    industria: "Manufactura",
    tamano: "1000+ emp.",
    ingresos: "$230M USD",
    scoreIA: 95,
    estado: "Contactada",
    sitio: "manufnorte.mx",
    contactos: 8,
    fechaAgregada: "2025-04-18",
  },
  {
    id: 9,
    nombre: "Cadena Fría SA",
    industria: "Logística",
    tamano: "100-200 emp.",
    ingresos: "$34M USD",
    scoreIA: 73,
    estado: "Investigada",
    sitio: "cadenafria.mx",
    contactos: 2,
    fechaAgregada: "2025-04-20",
  },
  {
    id: 10,
    nombre: "BioMédica Latina",
    industria: "Salud",
    tamano: "200-500 emp.",
    ingresos: "$78M USD",
    scoreIA: 85,
    estado: "En proceso",
    sitio: "biomedicalatina.mx",
    contactos: 4,
    fechaAgregada: "2025-04-22",
  },
];

export const contacts = [
  {
    id: 1,
    nombre: "Carlos Mendoza Reyes",
    iniciales: "CM",
    cargo: "Director General",
    empresa: "Grupo Industrial Monterrey",
    email: "c.mendoza@grupoindustrial.mx",
    linkedin: "linkedin.com/in/carlosmendoza",
    canalPreferido: "LinkedIn",
    estado: "Respondió",
    color: "blue",
  },
  {
    id: 2,
    nombre: "Alejandra Torres Vega",
    iniciales: "AT",
    cargo: "CFO",
    empresa: "Grupo Industrial Monterrey",
    email: "a.torres@grupoindustrial.mx",
    linkedin: "linkedin.com/in/alejandrat",
    canalPreferido: "Email",
    estado: "Contactado",
    color: "emerald",
  },
  {
    id: 3,
    nombre: "Roberto Jiménez Luna",
    iniciales: "RJ",
    cargo: "Director de Operaciones",
    empresa: "LogiTrans México",
    email: "r.jimenez@logitrans.mx",
    linkedin: "linkedin.com/in/robertoj",
    canalPreferido: "LinkedIn",
    estado: "Reunión agendada",
    color: "purple",
  },
  {
    id: 4,
    nombre: "María Elena García",
    iniciales: "MG",
    cargo: "Gerente de Compras",
    empresa: "LogiTrans México",
    email: "m.garcia@logitrans.mx",
    linkedin: "linkedin.com/in/mariaelena",
    canalPreferido: "WhatsApp",
    estado: "Respondió",
    color: "blue",
  },
  {
    id: 5,
    nombre: "Fernando López Castro",
    iniciales: "FL",
    cargo: "CEO",
    empresa: "Salud Integral SA",
    email: "f.lopez@saludintegral.mx",
    linkedin: "linkedin.com/in/fernandol",
    canalPreferido: "Email",
    estado: "Pendiente",
    color: "slate",
  },
  {
    id: 6,
    nombre: "Patricia Ruiz Moreno",
    iniciales: "PR",
    cargo: "Directora Médica",
    empresa: "Salud Integral SA",
    email: "p.ruiz@saludintegral.mx",
    linkedin: "linkedin.com/in/patriciar",
    canalPreferido: "LinkedIn",
    estado: "Contactado",
    color: "emerald",
  },
  {
    id: 7,
    nombre: "Héctor Ramírez Soto",
    iniciales: "HR",
    cargo: "VP Tecnología",
    empresa: "TechSoluciones MX",
    email: "h.ramirez@techsoluciones.mx",
    linkedin: "linkedin.com/in/hectorr",
    canalPreferido: "LinkedIn",
    estado: "Reunión agendada",
    color: "purple",
  },
  {
    id: 8,
    nombre: "Laura Hernández Paz",
    iniciales: "LH",
    cargo: "Directora Comercial",
    empresa: "Constructora Azteca",
    email: "l.hernandez@constructoraazteca.mx",
    linkedin: "linkedin.com/in/laurah",
    canalPreferido: "Email",
    estado: "Respondió",
    color: "blue",
  },
  {
    id: 9,
    nombre: "Miguel Ángel Flores",
    iniciales: "MF",
    cargo: "Gerente de Logística",
    empresa: "Distribuidora Nacional",
    email: "m.flores@distrinacional.mx",
    linkedin: "linkedin.com/in/miguelaf",
    canalPreferido: "WhatsApp",
    estado: "Pendiente",
    color: "slate",
  },
  {
    id: 10,
    nombre: "Ana Cristina Vargas",
    iniciales: "AV",
    cargo: "CFO",
    empresa: "Pharma Innovación",
    email: "a.vargas@pharmainnovacion.mx",
    linkedin: "linkedin.com/in/anacv",
    canalPreferido: "LinkedIn",
    estado: "Contactado",
    color: "emerald",
  },
  {
    id: 11,
    nombre: "Jorge Alberto Núñez",
    iniciales: "JN",
    cargo: "Director de Manufactura",
    empresa: "Manufactura del Norte",
    email: "j.nunez@manufnorte.mx",
    linkedin: "linkedin.com/in/jorgen",
    canalPreferido: "Email",
    estado: "Respondió",
    color: "blue",
  },
  {
    id: 12,
    nombre: "Sofía Morales Ibarra",
    iniciales: "SM",
    cargo: "Jefa de Cadena de Suministro",
    empresa: "Manufactura del Norte",
    email: "s.morales@manufnorte.mx",
    linkedin: "linkedin.com/in/sofiam",
    canalPreferido: "LinkedIn",
    estado: "Reunión agendada",
    color: "purple",
  },
  {
    id: 13,
    nombre: "Eduardo Castillo Vera",
    iniciales: "EC",
    cargo: "CEO",
    empresa: "Cadena Fría SA",
    email: "e.castillo@cadenafria.mx",
    linkedin: "linkedin.com/in/eduardoc",
    canalPreferido: "WhatsApp",
    estado: "Pendiente",
    color: "slate",
  },
  {
    id: 14,
    nombre: "Valentina Cruz Ríos",
    iniciales: "VC",
    cargo: "Directora de Innovación",
    empresa: "BioMédica Latina",
    email: "v.cruz@biomedicalatina.mx",
    linkedin: "linkedin.com/in/valentinac",
    canalPreferido: "LinkedIn",
    estado: "Contactado",
    color: "emerald",
  },
  {
    id: 15,
    nombre: "Ricardo Padilla Ortiz",
    iniciales: "RP",
    cargo: "Director General",
    empresa: "BioMédica Latina",
    email: "r.padilla@biomedicalatina.mx",
    linkedin: "linkedin.com/in/ricardop",
    canalPreferido: "Email",
    estado: "Respondió",
    color: "blue",
  },
];

export const campaigns = [
  {
    id: 1,
    nombre: "Manufactura Q2 2025",
    estado: "Activa",
    descripcion: "Campaña enfocada en empresas de manufactura con más de 200 empleados en el norte de México",
    contactos: 89,
    respuestas: 12,
    reuniones: 4,
    tasaRespuesta: 13.5,
    progreso: 68,
    fechaInicio: "2025-04-01",
    fechaFin: "2025-06-30",
    canal: "LinkedIn + Email",
    industria: "Manufactura",
  },
  {
    id: 2,
    nombre: "Logística Digital",
    estado: "Activa",
    descripcion: "Dirigida a directores de operaciones y logística en empresas con cadenas de suministro complejas",
    contactos: 67,
    respuestas: 18,
    reuniones: 3,
    tasaRespuesta: 26.9,
    progreso: 45,
    fechaInicio: "2025-04-15",
    fechaFin: "2025-07-15",
    canal: "LinkedIn",
    industria: "Logística",
  },
  {
    id: 3,
    nombre: "Salud Corporativa",
    estado: "Pausada",
    descripcion: "Campaña para hospitales y clínicas privadas en busca de soluciones de gestión administrativa",
    contactos: 45,
    respuestas: 7,
    reuniones: 0,
    tasaRespuesta: 15.6,
    progreso: 30,
    fechaInicio: "2025-03-01",
    fechaFin: "2025-05-31",
    canal: "Email + WhatsApp",
    industria: "Salud",
  },
];

export const weeklyChartData = [
  { semana: "Sem 1", contactos: 18, respuestas: 3, reuniones: 0 },
  { semana: "Sem 2", contactos: 24, respuestas: 5, reuniones: 1 },
  { semana: "Sem 3", contactos: 31, respuestas: 7, reuniones: 2 },
  { semana: "Sem 4", contactos: 28, respuestas: 8, reuniones: 1 },
  { semana: "Sem 5", contactos: 35, respuestas: 6, reuniones: 2 },
  { semana: "Sem 6", contactos: 42, respuestas: 9, reuniones: 3 },
  { semana: "Sem 7", contactos: 38, respuestas: 11, reuniones: 2 },
  { semana: "Sem 8", contactos: 45, respuestas: 10, reuniones: 4 },
];

export const recentActivity = [
  {
    id: 1,
    tipo: "respuesta",
    descripcion: "Carlos Mendoza respondió al mensaje de LinkedIn",
    empresa: "Grupo Industrial Monterrey",
    tiempo: "hace 2 horas",
    icon: "MessageSquare",
  },
  {
    id: 2,
    tipo: "reunion",
    descripcion: "Reunión agendada con Roberto Jiménez",
    empresa: "LogiTrans México",
    tiempo: "hace 4 horas",
    icon: "Calendar",
  },
  {
    id: 3,
    tipo: "contacto",
    descripcion: "Nuevo contacto agregado: Sofía Morales",
    empresa: "Manufactura del Norte",
    tiempo: "hace 6 horas",
    icon: "UserPlus",
  },
  {
    id: 4,
    tipo: "investigacion",
    descripcion: "Cuenta investigada: BioMédica Latina",
    empresa: "BioMédica Latina",
    tiempo: "hace 8 horas",
    icon: "Search",
  },
  {
    id: 5,
    tipo: "mensaje",
    descripcion: "Secuencia de emails enviada a 15 contactos",
    empresa: "Campaña Logística Digital",
    tiempo: "hace 10 horas",
    icon: "Send",
  },
];
